# TCL File Generated by Component Editor 18.1
# Tue Feb 20 20:59:13 EST 2024
# DO NOT MODIFY


# 
# avalon_control "avalon_control" v1.0
#  2024.02.20.20:59:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_control
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_control
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_control
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_control.sv SYSTEM_VERILOG PATH avalon_control.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_write write Input 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point av_clk
# 
add_interface av_clk clock start
set_interface_property av_clk associatedDirectClock ""
set_interface_property av_clk clockRate 0
set_interface_property av_clk clockRateKnown false
set_interface_property av_clk ENABLED true
set_interface_property av_clk EXPORT_OF ""
set_interface_property av_clk PORT_NAME_MAP ""
set_interface_property av_clk CMSIS_SVD_VARIABLES ""
set_interface_property av_clk SVD_ADDRESS_GROUP ""

add_interface_port av_clk av_clk clk Output 1


# 
# connection point av_reset
# 
add_interface av_reset conduit end
set_interface_property av_reset associatedClock clock
set_interface_property av_reset associatedReset reset
set_interface_property av_reset ENABLED true
set_interface_property av_reset EXPORT_OF ""
set_interface_property av_reset PORT_NAME_MAP ""
set_interface_property av_reset CMSIS_SVD_VARIABLES ""
set_interface_property av_reset SVD_ADDRESS_GROUP ""

add_interface_port av_reset av_reset export Output 1


# 
# connection point start_rt
# 
add_interface start_rt conduit end
set_interface_property start_rt associatedClock clock
set_interface_property start_rt associatedReset reset
set_interface_property start_rt ENABLED true
set_interface_property start_rt EXPORT_OF ""
set_interface_property start_rt PORT_NAME_MAP ""
set_interface_property start_rt CMSIS_SVD_VARIABLES ""
set_interface_property start_rt SVD_ADDRESS_GROUP ""

add_interface_port start_rt start_rt export Output 1

